### ISSUE TITLE
Please decouple `linguify`

### ISSUE THREAD

**Issue by ivaquero** [jomaway/typst-gentle-clues#9]
The new release can't read my local `lang.toml`, I'm sure it's caused by `linguify:0.3.0` that force me to use the package's `lang.toml`.

<img width="373" alt="image" src="https://github.com/jomaway/typst-gentle-clues/assets/46377665/9a7d3234-0ff0-4cba-83f3-81d155c6a173">

Could you please decouple `linguify`? I am not sure if it's against your design, however, I think fewer dependencies makes this package more flexible.

**Comment by jomaway** [comment]
How did you load your `lang.toml`? Did you use `linguify_set_databse(toml(your_lang.toml))` ?

**Comment by ivaquero** [comment]
Yes, I tried both of the functions, but get the same error.

**Comment by ivaquero** [comment]
Sure.

```toml
default-lang = "zh"

[en]
font = "Arial"
chapter = "Chapter"
content = "Content"
definition = "Definition"
theorem = "Theorem"
lemma = "Lemma"
corollary = "Corollary"
algorithm = "Algorithm"
alert = "Alert"
tip = "Tip"
eq = " Eq."

[zh]
font = "Songti SC"
chapter = "章节"
content = "主要内容"
definition = "定义"
theorem = "定理"
lemma = "引理"
corollary = "推论"
algorithm = "算法"
alert = "注意"
tip = "提示"
eq = "  式 "
```
